### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### mostjs/dom-event now has a Chat Room on Gitter

@briancavalier has just created a chat room. You can visit it here: [https://gitter.im/mostjs/dom-event](https://gitter.im/mostjs/dom-event?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/mostjs/dom-event?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by briancavalier** [comment]
@TylorS @davidchase Should we close this and just direct folks to the main most.js gitter chat?

**Comment by davidchase** [comment]
👍

**Comment by briancavalier** [comment]
@davidchase is your thumbs up for closing this? Just making sure :)

**Comment by davidchase** [comment]
yes sorry i think we can close in favor of the current gitter room

**Comment by briancavalier** [comment]
Cool, thanks. Closing.

**Pull request closed without merging**
